// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1679878511);
user_pref("app.update.lastUpdateTime.background-update-timer", 1679878705);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1679878585);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1679947044);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1679878825);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.dom.window.dump.enabled", false);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.lastAppBuildId", "20230312173626");
user_pref("extensions.lastAppVersion", "6.0.23");
user_pref("extensions.lastPlatformVersion", "60.9.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.zotero.dataDir", "/home/isaac/Zotero");
user_pref("extensions.zotero.export.lastTranslator", "f4b52ab0-f878-4556-85a0-c7aeedd09dfc");
user_pref("extensions.zotero.export.quickCopy.setting", "export=a515a220-6fef-45ea-9842-8025dfebcc8f");
user_pref("extensions.zotero.export.translatorSettings", "{\"keepUpdated\":true,\"worker\":true}");
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.ignoreLegacyDataDir.auto", true);
user_pref("extensions.zotero.lastViewedFolder", "C1");
user_pref("extensions.zotero.night.enabled", true);
user_pref("extensions.zotero.pane.persist", "{\"zotero-reader-sidebar-pane\":{\"collapsed\":\"false\",\"width\":\"240\"},\"zotero-collections-pane\":{\"width\":\"253\"},\"zotero-tags-splitter\":{},\"zotero-tag-selector-container\":{},\"zotero-collections-splitter\":{},\"zotero-layout-switcher\":{\"orient\":\"horizontal\"},\"zotero-items-pane\":{\"width\":\"1151\"},\"zotero-items-splitter\":{\"orient\":\"horizontal\"},\"zotero-item-pane\":{\"width\":\"502\",\"height\":\"300\"},\"zotero-context-splitter\":{\"state\":\"collapsed\"},\"zotero-context-pane\":{},\"zotero-context-splitter-stacked\":{\"state\":\"open\"},\"zotero-context-pane-inner\":{}}");
user_pref("extensions.zotero.prefVersion", 6);
user_pref("extensions.zotero.recentSaveTargets", "[{\"id\":\"C3\",\"sessionID\":\"sJHM9C58\"},{\"id\":\"C3\",\"sessionID\":\"7qlIPnkv\"},{\"id\":\"C3\",\"sessionID\":\"YGFLWIt8\"},{\"id\":\"C5\",\"sessionID\":\"Cs1xisNt\"},{\"id\":\"L1\",\"sessionID\":\"uBplK8Qj\"},{\"id\":\"C4\",\"sessionID\":\"dx3LtRNV\"}]");
user_pref("extensions.zotero.sourceList.persist", "{\"L1\":true,\"P1\":false,\"C2\":true,\"C1\":true}");
user_pref("extensions.zotero.sync.reminder.setUp.lastDisplayed", 1679364328);
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormatEditing", "auth.lower + shorttitle(3,3) + year");
user_pref("extensions.zotero.translators.better-bibtex.platform", "lin");
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zotfile.source_dir_ff", false);
user_pref("extensions.zotfile.version", "5.1.2");
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1679878783);
user_pref("intl.accept_languages", "en-US, en");
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("places.database.lastMaintenance", 1679367379);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 1);
user_pref("storage.vacuum.last.places.sqlite", 1679367379);
